### ISSUE TITLE
Mount /dev/xvdb properly for jenkins (as /var/lib/cjt)

### ISSUE THREAD

**Issue by mrichnu** [NorthwesternCloud/jenkins-instance-cfn#1]
Currently a 100GB volume is created and attached to the instance as /dev/xvdb. A partition needs to be created on that block device, taking up the entire volume, and a file system created on it, and added to /etc/fstab as /var/lib/cjt for the jenkins team installation.

**Comment by mrichnu** [comment]
Can use ansible:
http://docs.ansible.com/ansible/latest/parted_module.html
http://docs.ansible.com/ansible/latest/filesystem_module.html
http://docs.ansible.com/ansible/latest/mount_module.html

**Comment by jwalsh2me** [comment]
Changed the method and added a Block Device instead.

 BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
